# Generated by Django 5.0.6 on 2024-07-05 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_text', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('unit', 'Unit'), ('tablet', 'Tablet')], max_length=6)),
                ('dosage', models.IntegerField()),
                ('medication_date', models.DateField()),
                ('medication_time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user')),
            ],
        ),
        migrations.CreateModel(
            name='BSEntry',
            fields=[
                ('bpentry_id', models.AutoField(primary_key=True, serialize=False)),
                ('sugar', models.IntegerField()),
                ('measured', models.CharField(choices=[('Before Breakfast', 'Before Breakfast'), ('After Breakfast', 'After Breakfast'), ('Before Lunch', 'Before Lunch'), ('After Lunch', 'After Lunch'), ('Before Dinner', 'Before Dinner'), ('After Dinner', 'After Dinner')], max_length=20)),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user')),
            ],
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user')),
            ],
        ),
    ]
